version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /provider
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /sdk/dotnet
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /sdk
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /sdk/java
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /sdk/nodejs
    schedule:
      interval: daily
